import java.io.IOException;

public class ExceptionHandling{
	public static void main(String args[])
	{
		try{
			abc();
		}catch(IOException e){
			System.out.println(e.getMessage());
		}
		catch(UserException e) {
			System.out.println(e.getMessage());
		}
	}

	public static void abc() throws IOException, UserException
	{
		try{
			int a=15;
			for(int i=10;i<100;i++)
			{
				if(i==18)
					throw new UserException("Exception at:"+i);
				if(i==8)
					throw new IOException("IOException at:"+i);
				System.out.println(":-"+(a/(a-i)));
				
			}
		}catch(ArithmeticException e){
			System.out.println("Divide by zero!");
		}
	}
}

class UserException extends Exception{
	public UserException() {
		
	}
	public UserException(String message) {
		super(message);
	}
}